import fs from 'fs';
import path from 'path';

const existingPath = path.join(process.cwd(), 'data/events.json');
const existingEvents = JSON.parse(fs.readFileSync(existingPath, 'utf8'));

const catalog = [
  { id: "world-economic-forum-davos-2026", name: "World Economic Forum (Davos)", category: "summit", locationICAO: "LSZH", locationCity: "Davos, Switzerland", locationCountry: "Global", start: "2026-01-19", end: "2026-01-23", tier: 5, req: 600, price: 250000, dress: "Business formal with outerwear showmanship", desc: "The ultimate gathering of global leaders and billionaires. The official delegate pass is just the start—the real deals happen at the surrounding chalets." },
  { id: "sundance-film-festival-2026", name: "Sundance Film Festival", category: "art", locationICAO: "KHCR", locationCity: "Park City, UT", locationCountry: "Global", start: "2026-01-22", end: "2026-02-01", tier: 3, req: 0, price: 75000, dress: "Mountain chic, understated designer winterwear", desc: "The premier independent film festival where billionaires discreetly back future Oscar winners and host lodge parties." },
  { id: "australian-open-men-s-final-2026", name: "Australian Open (Men's Final)", category: "sport", locationICAO: "YMEN", locationCity: "Melbourne", locationCountry: "Global", start: "2026-01-24", end: "2026-01-26", tier: 3, req: 0, price: 45000, dress: "Summer smart casual", desc: "The first Grand Slam of the year. Rod Laver suite access is a must." },
  { id: "art-sg-frieze-la-winter-shows-2026", name: "Art SG / Frieze LA / Winter Shows", category: "art", locationICAO: "KVNY", locationCity: "Multiple", locationCountry: "Global", start: "2026-02-15", end: "2026-02-18", tier: 3, req: 0, price: 15000, dress: "Avant-garde luxury", desc: "The global art market's winter circuit. VIP previews are essential for early acquisitions." },
  { id: "super-bowl-2026", name: "Super Bowl", category: "sport", locationICAO: "KSJC", locationCity: "Santa Clara, CA", locationCountry: "Global", start: "2026-02-07", end: "2026-02-09", tier: 4, req: 0, price: 125000, dress: "Casual extreme luxury", desc: "The ultimate American sporting spectacle. Field-side suites are the standard." },
  { id: "bafta-awards-2026", name: "BAFTA Awards", category: "gala", locationICAO: "EGLL", locationCity: "London", locationCountry: "Global", start: "2026-02-16", end: "2026-02-17", tier: 4, req: 0, price: 40000, dress: "Black tie, British elegance", desc: "The pinnacle of British film awards and a gateway to the most exclusive after-parties." },
  { id: "oscars-vanity-fair-party-2026", name: "Oscars + Vanity Fair Party", category: "gala", locationICAO: "KVNY", locationCity: "Los Angeles", locationCountry: "Global", start: "2026-03-01", end: "2026-03-02", tier: 5, req: 550, price: 95000, dress: "Black tie, high couture", desc: "The biggest night in Hollywood. The ceremony is one thing, the Vanity Fair after-party is another." },
  { id: "paris-fashion-week-f-w-2026", name: "Paris Fashion Week (F/W)", category: "fashion", locationICAO: "LFPB", locationCity: "Paris", locationCountry: "Global", start: "2026-02-24", end: "2026-03-04", tier: 3, req: 0, price: 25000, dress: "High fashion, bold statements", desc: "Front-row access to the autumn/winter collections of the world's leading fashion houses." },
  { id: "milan-design-week-salone-del-mobile-2026", name: "Milan Design Week (Salone del Mobile)", category: "art", locationICAO: "LIML", locationCity: "Milan", locationCountry: "Global", start: "2026-04-07", end: "2026-04-13", tier: 3, req: 0, price: 30000, dress: "Italian smart casual", desc: "The global benchmark for the design and furniture sector. Private previews are fiercely contested." },
  { id: "coachella-weekend-1-2026", name: "Coachella Weekend 1", category: "music", locationICAO: "KTRM", locationCity: "Indio, CA", locationCountry: "Global", start: "2026-04-10", end: "2026-04-12", tier: 3, req: 0, price: 50000, dress: "Coded-cool desert chic", desc: "The iconic desert music festival. VIP Safari tents and exclusive artist compounds." },
  { id: "coachella-weekend-2-2026", name: "Coachella Weekend 2", category: "music", locationICAO: "KTRM", locationCity: "Indio, CA", locationCountry: "Global", start: "2026-04-17", end: "2026-04-19", tier: 2, req: 0, price: 30000, dress: "Coded-cool desert chic", desc: "The second weekend, slightly more relaxed but still an essential social event." },
  { id: "kentucky-derby-2026", name: "Kentucky Derby", category: "sport", locationICAO: "KLOU", locationCity: "Louisville", locationCountry: "Global", start: "2026-05-02", end: "2026-05-03", tier: 4, req: 0, price: 55000, dress: "Classic Southern formal + hats", desc: "The most exciting two minutes in sports. Millionaires Row access is non-negotiable." },
  { id: "met-gala-2026", name: "Met Gala", category: "gala", locationICAO: "KTEB", locationCity: "New York", locationCountry: "Global", start: "2026-05-04", end: "2026-05-05", tier: 5, req: 700, price: 250000, dress: "Thematic — whatever Anna decrees", desc: "Fashion's biggest night out. Highly exclusive invite list curated by Anna Wintour." },
  { id: "cannes-film-festival-2026", name: "Cannes Film Festival", category: "gala", locationICAO: "LFMD", locationCity: "Cannes", locationCountry: "Global", start: "2026-05-13", end: "2026-05-24", tier: 4, req: 0, price: 120000, dress: "Riviera black tie", desc: "A marathon of yacht parties, charity galas, and world premieres on the Croisette." },
  { id: "monaco-grand-prix-2026", name: "Monaco Grand Prix", category: "sport", locationICAO: "LFMN", locationCity: "Monaco", locationCountry: "Global", start: "2026-05-22", end: "2026-05-25", tier: 4, req: 400, price: 180000, dress: "Resort formal, nautical on Sunday", desc: "The crown jewel of the F1 calendar. Paddock access, Amber Lounge dinners, and the yacht parties that actually matter." },
  { id: "art-basel-basel-2026", name: "Art Basel Basel", category: "art", locationICAO: "LFSB", locationCity: "Basel", locationCountry: "Global", start: "2026-06-19", end: "2026-06-22", tier: 3, req: 0, price: 40000, dress: "European avant-garde", desc: "The original and most prestigious of the Art Basel fairs." },
  { id: "royal-ascot-2026", name: "Royal Ascot", category: "sport", locationICAO: "EGLF", locationCity: "Ascot, UK", locationCountry: "Global", start: "2026-06-17", end: "2026-06-21", tier: 4, req: 0, price: 35000, dress: "Morning suits, proper hats", desc: "Britain's most valuable race meeting. Royal Enclosure or adjacent required." },
  { id: "wimbledon-men-s-final-2026", name: "Wimbledon Men's Final", category: "sport", locationICAO: "EGLL", locationCity: "London", locationCountry: "Global", start: "2026-07-11", end: "2026-07-13", tier: 4, req: 0, price: 60000, dress: "Smart, restrained British summer wear", desc: "The oldest tennis tournament in the world. Centre Court debenture seats." },
  { id: "sun-valley-allen-co-conference-2026", name: "Sun Valley Allen & Co Conference", category: "summit", locationICAO: "KSUN", locationCity: "Sun Valley, ID", locationCountry: "Global", start: "2026-07-08", end: "2026-07-13", tier: 5, req: 800, price: 0, dress: "Billionaire casual (fleece vests)", desc: "The 'summer camp for billionaires'. Invite-only gathering of tech and media titans." },
  { id: "aspen-ideas-festival-2026", name: "Aspen Ideas Festival", category: "summit", locationICAO: "KASE", locationCity: "Aspen", locationCountry: "Global", start: "2026-06-28", end: "2026-07-04", tier: 4, req: 0, price: 75000, dress: "Mountain intellectual", desc: "A prestigious gathering of leaders and thinkers in the Rockies." },
  { id: "cowes-week-yacht-regatta-2026", name: "Cowes Week + yacht regatta", category: "season", locationICAO: "EGHI", locationCity: "Isle of Wight", locationCountry: "Global", start: "2026-08-02", end: "2026-08-09", tier: 3, req: 0, price: 25000, dress: "Nautical performance", desc: "One of the oldest and largest sailing regattas in the world." },
  { id: "monaco-yacht-show-2026", name: "Monaco Yacht Show", category: "season", locationICAO: "LFMN", locationCity: "Monaco", locationCountry: "Global", start: "2026-09-24", end: "2026-09-27", tier: 3, req: 0, price: 35000, dress: "Riviera smart casual", desc: "The premier event for large custom yachts. Dealer previews and owner dinners." },
  { id: "hamptons-season-watermill-ball-polo-2026", name: "Hamptons Season (Watermill Ball + polo)", category: "season", locationICAO: "KHTO", locationCity: "East Hampton", locationCountry: "Global", start: "2026-07-25", end: "2026-07-27", tier: 3, req: 0, price: 45000, dress: "Summer whites, linen", desc: "The peak weekend of the Hamptons summer season." },
  { id: "salzburg-festival-2026", name: "Salzburg Festival", category: "art", locationICAO: "LOWS", locationCity: "Salzburg", locationCountry: "Global", start: "2026-07-20", end: "2026-08-31", tier: 4, req: 0, price: 40000, dress: "European formal", desc: "The world's most significant festival of music and drama." },
  { id: "edinburgh-international-festival-2026", name: "Edinburgh International Festival", category: "art", locationICAO: "EGPH", locationCity: "Edinburgh", locationCountry: "Global", start: "2026-08-02", end: "2026-08-24", tier: 2, req: 0, price: 15000, dress: "Smart casual + layers", desc: "A world-class cultural event demanding VIP programming access." },
  { id: "burning-man-for-the-silicon-valley-set-2026", name: "Burning Man (for the Silicon Valley set)", category: "music", locationICAO: "KRNO", locationCity: "Black Rock Desert", locationCountry: "Global", start: "2026-08-24", end: "2026-09-01", tier: 2, req: 0, price: 30000, dress: "Desert survival couture", desc: "Plug-and-play camps, private chefs, and art car syndicates." },
  { id: "venice-film-festival-2026", name: "Venice Film Festival", category: "gala", locationICAO: "LIPZ", locationCity: "Venice", locationCountry: "Global", start: "2026-08-27", end: "2026-09-06", tier: 4, req: 0, price: 80000, dress: "Venetian black tie", desc: "The oldest film festival in the world. Hotel Cipriani access is key." },
  { id: "us-open-men-s-final-2026", name: "US Open Men's Final", category: "sport", locationICAO: "KTEB", locationCity: "New York", locationCountry: "Global", start: "2026-09-05", end: "2026-09-07", tier: 3, req: 0, price: 50000, dress: "New York smart casual", desc: "The final major of the year. Chase suite access." },
  { id: "milan-fashion-week-paris-fashion-week-s-s-2026", name: "Milan Fashion Week + Paris Fashion Week (S/S)", category: "fashion", locationICAO: "LIML", locationCity: "Milan / Paris", locationCountry: "Global", start: "2026-09-18", end: "2026-10-07", tier: 3, req: 0, price: 25000, dress: "Next season's runway", desc: "The critical Spring/Summer shows. Front row is essential." },
  { id: "frieze-london-frieze-masters-2026", name: "Frieze London + Frieze Masters", category: "art", locationICAO: "EGLC", locationCity: "London", locationCountry: "Global", start: "2026-10-15", end: "2026-10-19", tier: 3, req: 0, price: 20000, dress: "Urban chic", desc: "The center of the autumn art market. VIP previews and Masters dinners." },
  { id: "japanese-grand-prix-2026", name: "Japanese Grand Prix", category: "sport", locationICAO: "RJOZ", locationCity: "Suzuka", locationCountry: "Global", start: "2026-10-10", end: "2026-10-12", tier: 3, req: 0, price: 60000, dress: "Motorsport casual", desc: "One of the most challenging circuits. Paddock Club access." },
  { id: "pebble-beach-concours-d-elegance-2026", name: "Pebble Beach Concours d'Elegance", category: "season", locationICAO: "KMRY", locationCity: "Pebble Beach", locationCountry: "Global", start: "2026-08-16", end: "2026-08-18", tier: 4, req: 0, price: 70000, dress: "Coastal golf chic", desc: "The ultimate collector car event. Chairman's package and private auctions." },
  { id: "breeders-cup-2026", name: "Breeders' Cup", category: "sport", locationICAO: "KSAZ", locationCity: "Varies", locationCountry: "Global", start: "2026-10-31", end: "2026-11-01", tier: 3, req: 0, price: 40000, dress: "Equestrian formal", desc: "The World Championships of thoroughbred racing. Turf Club is mandatory." },
  { id: "cop-climate-summit-2026", name: "COP Climate Summit", category: "summit", locationICAO: "Varies", locationCity: "Varies", locationCountry: "Global", start: "2026-11-09", end: "2026-11-20", tier: 4, req: 0, price: 0, dress: "Business conservative", desc: "Global climate policy hub. Side events and private dinners are the real draw." },
  { id: "art-basel-miami-beach-2026", name: "Art Basel Miami Beach", category: "art", locationICAO: "KOPF", locationCity: "Miami", locationCountry: "Global", start: "2026-12-03", end: "2026-12-07", tier: 4, req: 0, price: 50000, dress: "Miami flashy art-chic", desc: "The parties are louder than the art. VIP previews, Soho Beach House, and yacht hopping." },
  { id: "kennedy-center-honors-2026", name: "Kennedy Center Honors", category: "gala", locationICAO: "KIAD", locationCity: "Washington DC", locationCountry: "Global", start: "2026-12-06", end: "2026-12-08", tier: 4, req: 0, price: 55000, dress: "Black tie", desc: "Washington's most glamorous night. Includes White House reception access." },
  { id: "abu-dhabi-grand-prix-2026", name: "Abu Dhabi Grand Prix", category: "sport", locationICAO: "OMAA", locationCity: "Abu Dhabi", locationCountry: "Global", start: "2026-12-05", end: "2026-12-07", tier: 3, req: 0, price: 85000, dress: "Desert resort wear", desc: "The extravagant finale of the F1 season. Paddock Club and Yas Marina yacht access." },
  { id: "venice-nye-gala-varies-2026", name: "Venice NYE Gala", category: "gala", locationICAO: "LIPZ", locationCity: "Venice", locationCountry: "Global", start: "2026-12-31", end: "2027-01-01", tier: 3, req: 0, price: 40000, dress: "Masquerade formal", desc: "Exclusive palazzo balls to ring in the new year." },
  { id: "st-barths-new-year-s-eve-2026", name: "St. Barths New Year's Eve", category: "season", locationICAO: "TFFJ", locationCity: "St. Barths", locationCountry: "Global", start: "2026-12-29", end: "2027-01-02", tier: 3, req: 0, price: 65000, dress: "Island elegance", desc: "The ultimate billionaire playground for NYE. Superyacht hopping in Gustavia." },
  { id: "aspen-new-year-s-2026", name: "Aspen New Year's", category: "season", locationICAO: "KASE", locationCity: "Aspen", locationCountry: "Global", start: "2026-12-26", end: "2027-01-02", tier: 3, req: 0, price: 55000, dress: "Après-ski lux", desc: "Private chalets, the Caribou Club, and ringing in the year on the slopes." },
  { id: "miami-grand-prix-2026", name: "Miami Grand Prix", category: "sport", locationICAO: "KMIA", locationCity: "Miami", locationCountry: "Global", start: "2026-05-02", end: "2026-05-04", tier: 3, req: 0, price: 95000, dress: "Miami flashy", desc: "F1 meets Miami nightlife. High energy and exorbitant VIP hospitality." },
  { id: "silverstone-british-gp-2026", name: "Silverstone British GP", category: "sport", locationICAO: "EGLF", locationCity: "Silverstone", locationCountry: "Global", start: "2026-07-04", end: "2026-07-06", tier: 3, req: 0, price: 80000, dress: "Motorsport casual", desc: "The birthplace of F1. Paddock Club access with British understatement." },
  { id: "singapore-grand-prix-2026", name: "Singapore Grand Prix", category: "sport", locationICAO: "WSSS", locationCity: "Singapore", locationCountry: "Global", start: "2026-10-03", end: "2026-10-05", tier: 3, req: 0, price: 70000, dress: "Tropical business casual", desc: "F1's original night race. Extreme hospitality in the Paddock Club." },
  { id: "dubai-air-show-2026", name: "Dubai Air Show", category: "season", locationICAO: "OMDB", locationCity: "Dubai", locationCountry: "Global", start: "2026-11-15", end: "2026-11-19", tier: 3, req: 0, price: 50000, dress: "Business formal", desc: "Where billionaires shop for their next private jet. Highly exclusive pavilions." },
  { id: "formula-e-monaco-2026", name: "Formula E Monaco", category: "sport", locationICAO: "LFMN", locationCity: "Monaco", locationCountry: "Global", start: "2026-05-08", end: "2026-05-09", tier: 2, req: 0, price: 30000, dress: "Resort smart casual", desc: "The sustainable alternative, growing heavily in prestige on the Riviera." }
];

const newEvents = catalog.map(c => {
  const existing = existingEvents.find(e => e.id === c.id) || existingEvents.find(e => e.name === c.name);
  
  return {
    id: c.id,
    name: c.name,
    category: c.category,
    locationICAO: c.locationICAO,
    locationCity: c.locationCity,
    locationCountry: c.locationCountry || "Global",
    startDate: `${c.start}T00:00:00.000Z`,
    endDate: `${c.end}T23:59:59.000Z`,
    prestigeTier: c.tier,
    prestigeRequired: c.req,
    ticketPrice: c.price,
    dressCode: c.dress || "Event appropriate",
    description: c.desc,
    imageUrl: existing && existing.imageUrl ? existing.imageUrl : null,
    confirmedAttendees: existing && existing.confirmedAttendees ? existing.confirmedAttendees : []
  };
});

fs.writeFileSync(existingPath, JSON.stringify(newEvents, null, 2));
console.log(`Successfully mapped ${newEvents.length} events perfectly into events.json.`);
